language: java
jdk:
  - oraclejdk7
  - openjdk7
#node_js:
#  - "0.10"
services:
  - rabbitmq
  - elasticsearch
#  - logstash??
before_install:
  - sudo sed -i -e 's/^Defaults\tsecure_path.*$//' /etc/sudoers # remove secure path option
install:
  - npm install -g forever #node is installed by default, but cannot specify the version in this file.
  - ./scripts/install_etcd.sh
  - sudo ./scripts/install-titan.sh 0.4.4 localhost
before_script:
  - sudo ./scripts/setup-stucco.sh
  - sudo ./scripts/setup-config.sh
  - sudo ./scripts/start-stucco.sh
  - sudo ./scripts/load-stucco-data.sh
script:
  - sudo ./scripts/run-stucco-tests.sh
  - sudo ./scripts/test-db.sh